import './commands/rsrcCreate'
import './commands/rsrcCreateMongo'
import './commands/rsrcCreateMongoCrud'
import './commands/rsrcCreateEs'
import './commands/rsrcCreateEsCrud'
import './commands/rsrcAddPartial'
import './commands/rsrcAddRoute'
import './commands/rsrcAddEsIndices'
