const ES_ODM_CONFIG = `#
##### OpenSearch Config
OPENSEARCH_PROTOCOL=http
OPENSEARCH_DOMAIN=localhost:9200
OPENSEARCH_AUTH_ENABLED=true
OPENSEARCH_USERNAME=admin
OPENSEARCH_PASSWORD=Admin@123`

export default ES_ODM_CONFIG
